### PR TITLE
GitHub (Enterprise) fixes

### LINKED ISSUE #16: Deprecation warning for GitHub login
When building, the following deprecation warning is shown:

```
DeprecationWarning: Argument login_or_token is deprecated, please use auth=github.Auth.Token(...) instead
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocs_git_committers_plugin/plugin.py", line 38, in on_config
    self.github = Github( base_url="https://" + self.config['enterprise_hostname'] + "/api/v3", login_or_token=self.config['token'] )
  File "/opt/homebrew/lib/python3.11/site-packages/github/MainClass.py", line 177, in __init__
    warnings.warn(
```

### PR DESCRIPTION
**Pull request by cyb3rko**
Fixes #16  
And fixes one part of #17 (wrong URLs when clicking the author names)

### CODE REVIEW

**Comment by mihaigalos** [comment]
Hi @cyb3rko: did you actually get this running? The URLs to users profiles seem fixed with your changes, but I still cannot download users' avatars. Tried manually downloading it with curl (even with a bearer token) - nope.

Seems this is a known problem for GitHub Enterprise: https://github.com/octokit/octokit.js/discussions/2061#discussioncomment-553828.

**Comment by mihaigalos** [comment]
I got this running by scripting Selenium.

<details><summary>Details</summary>
<p>

```python
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.keys import Keys
import time
import os

start_url = "https://idp.company.com/idp/startSSO.ping?PartnerSpId=https://github.company.com"
username = "none"
password = os.getenv("GH_TOKEN")
avatar_url = "https://avatars.github.company.com/u/9214?&size=32"
download_path = "avatar.jpg"

chrome_options = Options()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--disable-gpu")
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--disable-extensions")
chrome_options.add_argument("--disable-infobars")
chrome_options.add_argument("--disable-notifications")
chrome_options.add_argument("--window-size=1920,1080")

driver = webdriver.Chrome(options=chrome_options)

try:
    driver.get(start_url)
    time.sleep(3)

    location_dropdown = Select(driver.find_element(By.ID, "location"))
    location_dropdown.select_by_value("HO")
    time.sleep(1)

    sign_on_button = driver.find_element(By.CSS_SELECTOR, "a.ping-button.normal.allow[title='Sign On']")
    sign_on_button.click()
    time.sleep(5)

    driver.get(avatar_url)
    time.sleep(3)

    avatar_element = driver.find_element(By.TAG_NAME, "img")
    with open(download_path, "wb") as file:
        file.write(avatar_element.screenshot_as_png)

    print(f"Avatar downloaded successfully to {download_path}.")

finally:
    driver.quit()
```

</p>
</details>

**Comment by mihaigalos** [comment]
Also, this seems to run when rendering from CI and pushing to gh-pages.
That's because the user's browser is authenticated via the OAuth workflow and thus the icons load.

They only locally don't work.

**Comment by cyb3rko** [comment]
Hello @mihaigalos,

I remember having issues with the avatars, but I'm currently not sure if I fixed it or not.  
Next week I will check again on the wiki I built and come back to you.

**Comment by timvink** [comment]
Fyi this repo had been forked, the fork has support for avatars and is actively maintained https://github.com/ojacques/mkdocs-git-committers-plugin-2

**Comment by cyb3rko** [comment]
> Fyi this repo had been forked, the fork has support for avatars and is actively maintained https://github.com/ojacques/mkdocs-git-committers-plugin-2 

Nice, good to know. Then I can close this here as it seems to be implemented in https://github.com/ojacques/mkdocs-git-committers-plugin-2

**Pull request closed without merging**
